name: Deploy development

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy development
    runs-on: [self-hosted, ai-code-review-trainer]

    steps:
      - name: Deploy dev app
        run: |
          cd ~/apps/ai-code-review-trainer
          git fetch origin
          git checkout dev
          git reset --hard origin/dev
          docker compose -f docker-compose.dev.yml up -d --build --force-recreate
          docker image prune -af
          docker builder prune -af --filter "until=24h"
